# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

Category.destroy_all
Location.destroy_all
User.destroy_all
Project.destroy_all
Faq.destroy_all
Reward.destroy_all
Pledge.destroy_all
ActiveRecord::Base.connection.reset_pk_sequence!('users')
ActiveRecord::Base.connection.reset_pk_sequence!('rewards')
ActiveRecord::Base.connection.reset_pk_sequence!('projects')
ActiveRecord::Base.connection.reset_pk_sequence!('pledges')
ActiveRecord::Base.connection.reset_pk_sequence!('locations')
ActiveRecord::Base.connection.reset_pk_sequence!('faqs')
ActiveRecord::Base.connection.reset_pk_sequence!('categories')

 category1 = Category.create(name: 'Art')
 category2 = Category.create(name: 'Comics')
 category3 = Category.create(name: 'Crafts')
 category4 = Category.create(name: 'Dance')
 category5 = Category.create(name: 'Design')
 category6 = Category.create(name: 'Fashion')
 category7 = Category.create(name: 'Film & Video')
 category8 = Category.create(name: 'Food')
 category9 = Category.create(name: 'Games')
category10 = Category.create(name: 'Journalism')
category11 = Category.create(name: 'Music')
category12 = Category.create(name: 'Photography')
category13 = Category.create(name: 'Publishing')
category14 = Category.create(name: 'Technology')
category15 = Category.create(name: 'Theater')

location1 = Location.create(name: 'New York City, NY')
location2 = Location.create(name: 'Los Angeles, CA')
location3 = Location.create(name: 'Chicago, IL')
location4 = Location.create(name: 'San Francisco, CA')
location5 = Location.create(name: 'Boston, MA')
location6 = Location.create(name: 'San Diego, CA')
location7 = Location.create(name: 'Washington, D.C.')
location8 = Location.create(name: 'Denver, CO')
location9 = Location.create(name: 'Phoenix, AZ')
location10 = Location.create(name: 'San Jose, CA')

user1 = User.create!(name: Faker::Name.name, email: 'starwars', password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user2 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user3 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user4 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user5 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user6 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user7 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user8 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user9 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user10 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user11 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user12 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user13 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user14 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user15 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user16 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user17 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user18 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user19 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))
user20 = User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "starwars", location_id: rand(1..10), biography: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4))

project1 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project2 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project3 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project4 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project5 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project6 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project7 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project8 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project9 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project10 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project11 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project12 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project13 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project14 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project15 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project16 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project17 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project18 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project19 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))
project20 = Project.create!(author_id: rand(1..20), title: Faker::Lorem.sentence, description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false, random_sentences_to_add: 4), category_id: rand(1..10), location_id: rand(1..10), goal: rand(1000..100000), risks: Faker::ChuckNorris.fact, start_date: Faker::Date.between(from: 1.year.ago, to: Date.today), end_date: Faker::Date.between(from: Date.today, to: 1.year.from_now))

faq1 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq2 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq3 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq4 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq5 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq6 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq7 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq8 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq9 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq10 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq11 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq12 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq13 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq14 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq15 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq16 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq17 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq18 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq19 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq20 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq21 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq22 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq23 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq24 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq25 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq26 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq27 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq28 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq29 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq30 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq31 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq32 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq33 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq34 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq35 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq36 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq37 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq38 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq39 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq40 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq41 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq42 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq43 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq44 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq45 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq46 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq47 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq48 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq49 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)
faq50 = Faq.create!( project_id: rand(1..20), question: Faker::Lorem.sentence, answer: Faker::Lorem.sentence)

reward1 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward2 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward3 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward4 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward5 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward6 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward7 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward8 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward9 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward10 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward11 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward12 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward13 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward14 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward15 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward16 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward17 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward18 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward19 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward20 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward21 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward22 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward23 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward24 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward25 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward26 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward27 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward28 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward29 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward30 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward31 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward32 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward33 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward34 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward35 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward36 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward37 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward38 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward39 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward40 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward41 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward42 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward43 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward44 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward45 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward46 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward47 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward48 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward49 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)
reward50 = Reward.create!( pledge_amount: rand(5..1000), title: Faker::Lorem.sentence,  description: Faker::Lorem.paragraph(sentence_count: 2, supplemental: false), delivery_date: Faker::Date.between(from: Date.today, to: 1.year.from_now), limit: rand(1..100), project_id: rand(1..20), shipping_type: Faker::Lorem.sentence)


pledge1 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge2 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge3 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge4 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge5 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge6 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge7 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge8 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge9 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge10 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge21 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge41 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge51 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge31 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge22 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge42 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge52 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge32 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge23 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge43 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge53 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge33 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge24 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge44 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge54 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge34 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge25 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge45 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge55 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge35 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge26 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge46 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge56 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge36 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge27 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge47 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge57 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge37 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge28 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge48 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge58 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge38 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge29 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge49 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge59 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge39 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge20 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge40 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge50 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))
pledge30 = Pledge.create!(pledge_id: rand(1..20),pledge_amount: rand(5..1000),reward_id: rand(1..50))